name: MacOS CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc8:
    name: GNU GCC 8
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build tweedledum
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/local/opt/gcc@8/bin/g++-8 -DTWEEDLEDUM_TESTS=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests

  build-gcc9:
    name: GNU GCC 9
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build tweedledum
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/local/opt/gcc/bin/g++-9 -DTWEEDLEDUM_TESTS=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests

  build-clang9:
    name: Clang 9
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build tweedledum
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -DTWEEDLEDUM_TESTS=ON  ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests